### PR TITLE
Move project to Python package

### PR DESCRIPTION
**Pull request by breitburg**
It will be much more convenient to install and use.

## Install

1. Using `pip`:
```bash
pip install .
```

2. Using `setuptools`:
```bash
python setup.py install
```

## Using

After installing pacakge just open terminal and type:

```console
$ discord_monitor
```

## Notes

- If you deploy this package on PyPi, then it can be easily installed. It would be cool.

- Need to think a little about the name of the package if you do merge anyway :)

### CODE REVIEW

**Comment by TaPO4eg3D** [comment]
I think it's a good idea. I will check PR tomorrow

**Review by breitburg — COMMENTED** [review]
Spasibo :)

**Comment by breitburg** [comment]
Chtozh, are we going to merge?

**Comment by TaPO4eg3D** [comment]
Very busy week. I hope I will have time today at evening to deploy the project to PyPi.

**Comment by TaPO4eg3D** [comment]
Actually, looks like there will be no use for this project soon: https://webrtc-review.googlesource.com/c/src/+/148768

**Pull request closed without merging**
